obj-m := fact.o

modules:
	make -C /usr/src/linux-headers-$(shell uname -r) M=$(PWD) $@

clean:
	make -C /usr/src/linux-headers-$(shell uname -r) M=$(PWD) $@obj-m := fact.o

modules:
	make -C /usr/src/linux-headers-$(shell uname -r) M=$(PWD) $@

clean:
	make -C /usr/src/linux-headers-$(shell uname -r) M=$(PWD) $@
